### ISSUE TITLE
Add dependencies to README.md

### ISSUE THREAD

**Issue by jjpe** [tudelft-pl/master-thesis-template#1]
I'm trying to build this template, and am running into build issues.

First there are the dependencies I've identified so far: 
`cleveref xargs xltxtra sourcecodepro mathabx`

At least on Fedora, these can be installed using `dnf`.  I'm thinking it might be good to make these explicit in the README.md.

But then there's `fvextra`, which seems to require manual setup by building from its [github](https://github.com/gpoore/fvextra/tree/master/fvextra) repo.  
Could this dependency (and others like it, if there are any) be installed by the build scripts?

For the record, this is as far as I've gotten so far, there may be more dependencies in either group.

**Comment by jjpe** [comment]
I think I have the complete dependency list now.

These are the necessary packages:
* fvextra (Fedora doesn't provide this)
* cleveref
* xargs
* xltxtra
* sourcecodepro
* mathabx
* upquote
* xstring
* framed
* wrapfig
* todonotes
* biblatex
* pgfopts
* xassoccnt
* menukeys
* acronym

In addition, the `biber` utility also needs to be installed.

**Comment by Virtlink** [comment]
I removed the dependency on `fvextra`, and added a list of direct dependencies to the readme. I think some of the dependencies you list are transitive dependencies of packages, which is why I recommend installing the full TexLive distribution.
