### ISSUE TITLE
Bibliography citation style issue

### ISSUE THREAD

**Issue by jjpe** [tudelft-pl/master-thesis-template#3]
When citing a bibliography item, the style is extremely verbose.
As a concrete example, I expect something like `Each message is a JSON[2] object with 4 fields.`.
Instead, I get `Each message is a JSONThe JSON website 2018 object with 4 fields.`

Of course I did some googling, but all I could find was [this](https://www.sharelatex.com/learn/Bibtex_bibliography_styles). However, adding a `\bibliographystyle{stylename}` entry just plain borks the build, so I'm not sure how to get rid of this verbose style.

**Comment by Virtlink** [comment]
The template uses Biblatex, not Bibtex. In `document.sty`, in this part:

```
% Bibliography
\usepackage[
  backend=biber,
  style=authoryear
]{biblatex}
```

Change the `style` to `numeric`. However, in a thesis you should use the verbose style, as your space is not limited.

**Comment by jjpe** [comment]
Thanks for the info.

For me it's not a matter of style but readability: the inserted text breaks up sentences really poorly, see the example I gave earlier.
Thus using the numeric style has my preference.
